---

- name: host
  debug: msg="{{ item }}"
  with_items:
     - "{{ groups['server'] }}"
#- name: GET CONSUL AGENT ZIP FILE 
#  get_url: url={{ consul.zip }} dest={{ consul.dest }} validate_certs=False
- name: COPY ZIP FILE
  copy: src={{ consul.zip_name }} dest={{ consul.dest }} owner=consul group=consul mode=0755
- name: UNZIP AND COPY THE BINERY TO /usr/bin
  unarchive: src={{ consul.dest }}{{ consul.zip_name }} dest={{ consul.path }} copy=no
- name: ADD CONSUL USER
  user: name=consul
- name: CREATE DIR STRUCTURE
  file: path={{ item }} state=directory mode=0755 owner=consul group=consul
  with_items:
     - /etc/consul.d
     - /etc/consul.d/bootstrap
     - /etc/consul.d/server
     - /etc/consul.d/client
     - /var/consul
- name: BOOTSTRAP TEMPLATE FILES
  template: src=bootstrap_config.json dest=/etc/consul.d/bootstrap/config.json owner=consul group=consul mode=0755
- name: SERVER TEMPLATE FILES
  template: src=server_config.json dest=/etc/consul.d/server/config.json owner=consul group=consul mode=0755
- name: CLIENT TEMPLATE FILES
  template: src=client_config.json dest=/etc/consul.d/client/config.json owner=consul group=consul mode=0755
- name: INIT SCRIPT
  template: src=script/init_consul.sh dest=/etc/consul.d/ mode=0755

#- name: CHECK STATUS
#  shell: /etc/consul.d/init_consul.sh status
#  register: result
#  ignore_errors: True
#- name: TEST
#  debug:
#    var: result
