consul:
  zip: https://releases.hashicorp.com/consul/0.6.4/consul_0.6.4_linux_amd64.zip
  dest: /tmp/
  zip_name: consul_0.6.4_linux_amd64.zip
  path: /usr/bin
  bootstrap: 192.168.33.10
  datacenter: COMCAST_DC1
  data_dir: /var/consul
  encrypt: bd48o/p+p6OWNMmyLU7Ktg==
