---

- name: SERVICES TEMPLATE FILES
  template: src=services.json dest=/etc/consul.d/client/ owner=consul group=consul mode=0755
- name: DOCKER DAEMON MONITOR SCRIPT
  template: src=docker.sh dest=/usr/local/bin/ mode=0755
#- name: HTTPD DAEMON MONITOR SCRIPT
#  template: src=httpd.sh dest=/usr/local/bin/ mode=0755
- name: START AS CLIENT
  shell: /etc/consul.d/init_consul.sh start client
- name: RESTART REGISTRATOR IF EXIST
  shell: docker restart registrator
  register: result
  ignore_errors: True
#- name: print
#  debug: msg="{{ result }}"
- name: START REGISTRATOR
  shell: docker run -d --name=registrator --net=host --volume=/var/run/docker.sock:/tmp/docker.sock gliderlabs/registrator:latest consul://localhost:8500
  when: result.failed is defined
