---

- name: CHECK STATUS
  shell: /etc/consul.d/init_consul.sh status
  register: result
  ignore_errors: True

- name: TEST
  debug:
    var: result
- name: BOOTSTRAP SERVER
  debug: msg="{{ groups.bootstrap }}"
